/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gzx_ndk_build_NativeUtils */

#ifndef _Included_com_example_gzx_ndk_build_NativeUtils
#define _Included_com_example_gzx_ndk_build_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gzx_ndk_build_NativeUtils
 * Method:    getAge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_gzx_ndk_1build_NativeUtils_getAge
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
